### ISSUE TITLE
camera always in use

### ISSUE THREAD

**Issue by Mudassir-cpu** [videosdk-live/videosdk-rtc-ios-sdk#14]
when I leave the meeting, my phone always show camera in use.

**Comment by udayg24** [comment]
@Mudassir-cpu thanks for pointing it out, it will be fixed with the next update

**Comment by udayg24** [comment]
thanks for the input, as of now, the camera issue has been resolved

**Comment by Mudassir-cpu** [comment]
@udayg24 issue still persists in v2.1.9, after leaving call, I can see cam in usage by our App in privacy

**Comment by udayg24** [comment]
are you using our public example for this or you have your own app?

**Comment by Mudassir-cpu** [comment]
i have my own app, i'm using same code just like you provided in your example project

**Comment by Mudassir-cpu** [comment]
@udayg24 any update?

**Comment by udayg24** [comment]
we have identified the issue, it will be fixed in next update.

**Comment by Mudassir-cpu** [comment]
waiting for new update with fix

**Comment by udayg24** [comment]
we will try to release it next week

**Comment by Mudassir-cpu** [comment]
@udayg24 any update?

**Comment by Mudassir-cpu** [comment]
our live users are facing this issue and this is critical bug, due to privacy insecurity.

**Comment by udayg24** [comment]
did you try 2.2.0?

**Comment by Mudassir-cpu** [comment]
Nope

**Comment by udayg24** [comment]
we aren’t encountering this issue. i’ve tested it in various SwiftUI/UiKit-based example applications. try deleting the derived data, removing podfile.lock and pods folder, and reinstalling the SDK. then, check if the issue persists.

**Comment by Mudassir-cpu** [comment]
yes this issue resolved, but not others

**Comment by Mudassir-cpu** [comment]
please open this issue
